### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by happymlearner** [amalapuram/handling_CI_in_CL-based-NIDS#1]
Hi 
I am working on this code IACB config but having error in line 44....from where the CICIDS2017_Class-wise-normalized_datasets/ will be accessed or this is to be created separately.

data = np.load("./CICIDS2017_Class-wise-normalized_datasets/"+name1,allow_pickle=True) # loads the individual data for each class

**Comment by amalapuram** [comment]
Hello @happymlearner ,


Workaround
-----------------
You need to split the output (dataframe) of the preprocess_dataset_ids17.py classwise and name it according to their corresponding class label. Place them in the CICIDS2017_Class-wise-normalized_datasets directory. Don't forget to concatenate  dataset with labels while doing the aforementioned step.

Actual Fix
-------------

We will update the codebase soon to reflect the changes

Hope this helps

**Comment by amalapuram** [comment]
Hello @happymlearner 

The data preprocessing file is updated, your issue will be resolved. please check and close this issue
